project:
  type: book
  preview: 
      port: 4700

filters:
  - abstract-section

book:
  title: Towards Optogenetic Feedback Control of Neural Population Dynamics
  subtitle: |
    Thesis Proposal \
    Biomedical Engineering PhD Program \
    Georgia Institute of Technology and Emory University 

  author: Kyle Johnsen
  date: 1/13/2023

  repo-url: https://github.com/kjohnsen/phd-proposal/
  downloads: [pdf]
  chapters:
    - index.qmd
    - src/specific-aims.qmd
    - src/background.qmd
    - src/aim1.qmd
    - src/aim2.qmd
    - src/aim3.qmd
    - src/timeline.qmd
    - src/references.qmd

bibliography: references.bib

execute: 
  freeze: auto
  cache: true

format:
  html:
    theme:
      dark: [darkly, theme.scss, theme-dark.scss]
      light: [flatly, theme.scss]
    number-depth: 1
    toc-depth: 4
    filters:
    - lightbox
    lightbox: auto
    csl: science.csl

  pdf:
    documentclass: gatechthesis
    # template: gtthesis.tex
    template-partials: 
      - latex/title.tex
      - latex/toc.tex
      - latex/before-body.tex
      - latex/after-body.tex
      - latex/biblio.tex
    papersize: letter
    fontsize: 12pt
    include-in-header: latex/header.tex
    cite-method: biblatex
    latex-auto-install: true
    fontfamily: mathptmx
    # mainfont: TeX Gyre Pagella
    # mathfont: TeX Gyre Pagella Math
    # sansfont: Open Sans
    # colorlinks: true
    link-citations: true
    # latex-max-runs: 1
    # keep-tex: true
    crossref: 
      fig-prefix: ""  # since somehow it was getting Figure Figure
      sec-prefix: ""  # since somehow it was getting Section subsection
    pdf-engine: pdflatex  # couldn't change font otherwise
