project:
  type: book
  preview: 
      port: 4700

filters:
  - abstract-section

book:
  title: Developing and exploiting optogenetic feedback control in mesoscale neuroscience
  subtitle: |
    Thesis Proposal \
    Biomedical Engineering PhD Program \
    Georgia Institute of Technology and Emory University 

  author: Kyle Johnsen
  date: 10/20/2022

  repo-url: https://github.com/kjohnsen/phd-proposal/
  downloads: [pdf]
  chapters:
    - index.qmd
    - specific-aims.qmd
    - background.qmd
    - aim1.qmd
    - aim2.qmd
    - aim3.qmd
    # - timeline.qmd
    - references.qmd

bibliography: references.json
csl: science.csl

execute: 
  freeze: auto
  cache: true

format:
  html:
    theme:
      dark: [darkly, theme.scss, theme-dark.scss]
      light: [flatly, theme.scss]
    number-depth: 1
    toc-depth: 4
    filters:
    - lightbox
    lightbox: auto

  pdf:
    documentclass: scrreprt
    papersize: letter
    include-in-header: header.tex
    latex-auto-install: true
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
    sansfont: Open Sans
    colorlinks: true



