project:
  type: book

book:
  title: "Improving and applying closed-loop optogenetic control in mesoscale neuroscience"
  author: "Kyle Johnsen"
  date: "10/20/2022"
  repo-url: https://github.com/kjohnsen/phd-proposal/
  downloads: [pdf]
  chapters:
    - index.qmd
    - summary.qmd
    - specific-aims.qmd
    - background.qmd
    - aim1/aim1.qmd
    - aim2/aim2.qmd
    - aim3/aim3.qmd
    - timeline.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly
    number-depth: 1
    toc-depth: 4

  pdf:
    documentclass: scrreprt
    papersize: letter
    include-in-header: header.tex
    fontfamily: libertinus
    colorlinks: true



