project:
  type: book
  preview: 
      port: 4700


book:
  title: Developing and exploiting optogenetic feedback control in mesoscale neuroscience
  subtitle: |
    Thesis Proposal \
    Biomedical Engineering PhD Program \
    Georgia Institute of Technology and Emory University 

  author: Kyle Johnsen
  date: 10/20/2022
  abstract: |
    As the importance of causal inference becomes increasingly recognized in neuroscience, the need for technology enabling precise manipulation of neural variables becomes apparent.  Feedback control is an important class of such manipulations for its ability to increase inference power by reducing response variability.  Widely used throughout the engineering disciplines, it has had a significant impact through a variety of techniques (e.g., voltage clamp, dynamic clamp) on cellular neuroscience.  However, feedback control has yet to be widely applied at the mesoscale/circuit level despite recent improvements in interfacing technology, such as optogenetics.  Challenges to adoption include the complexity of implementing fast closed-loop experiments, the need to adapt the mature methods of control theory to the idiosyncratic constraints of systems neuroscience experiments, and the lack of established technical guidelines for applying feedback control to address complex scientific questions.

    In this work I propose to begin to address these challenges in three aims. In Aim 1, I develop a simulation framework for easily prototyping closed-loop optogenetic control (CLOC) experiments in silico, thus allowing neuroscientists to test and iterate on experimental designs without the costs of in-vivo experiments or up-front investments in compatible hardware-software systems. In Aim 2, I will translate sophisticated model-based feedback control algorithms to the realistic experimental setting of bidirectional CLOC—the simultaneous use of both excitatory and inhibitory opsins. I will demonstrate some advantages of bidirectional CLOC and how it is not well accommodated by the algorithms previously demonstrated. Finally, in Aim 3, I will explore how recording, stimulation, and control requirements vary in an example application of CLOC—controlling the latent dynamics of simulated neural population activity and assessing their causal relationship with behavior. I will model this population activity with recurrent spiking neural networks trained using state-of-the-art, biologically plausible methods, with differing degrees of brain-like architecture and task complexity. This work will thus provide the systems neuroscience community with a more accessible entry point for CLOC, more powerful algorithms for leveraging bidirectional control, and a point of reference for designing CLOC experiments capable of answering complex scientific questions.

  repo-url: https://github.com/kjohnsen/phd-proposal/
  downloads: [pdf]
  chapters:
    - index.qmd
    - specific-aims.qmd
    - background.qmd
    - aim1.qmd
    - aim2.qmd
    - aim3.qmd
    - timeline.qmd
    - references.qmd

bibliography: references.json
csl: science.csl

execute: 
  freeze: auto

format:
  html:
    theme:
      dark: darkly
      light: flatly
    number-depth: 1
    toc-depth: 4
    filters:
    - lightbox
    lightbox: auto

  pdf:
    documentclass: scrreprt
    papersize: letter
    # include-in-header: header.tex
    latex-auto-install: true
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
    sansfont: Open Sans
    colorlinks: true
    # not working
    hyperrefoptions: 
      - "backref=true"
      - "linktoc=all"



