# Aim 2: Bidirectional CLOC {#sec-aim2}

## Rationale
### Advantages of bidirectional control
The power of closed-loop optogenetic control (CLOC, henceforth referring specifically to feedback control; see @sec-cl-types) is limited by the degrees of freedom provided by the optogenetic actuation scheme.
One important distinction in possible actuation schemes is between "unidirectional"---control by a single opsin type---and "bidirectional"---where both excitatory and inhibitory opsins are used.
Unidirectional control has obvious shortcomings: for example, an excitatory opsin alone can only raise the firing rate of target neurons, not lower it or even clamp to a baseline level.
This setup would also be unable to *lower* the firing rate quickly, in the case of a dynamic reference trajectory.

### Advantages of model-based, optimal control
While a previous study [@newman15] has already laid the foundation for bidirectional CLOC, it does not feature the generalizability and scalability of the model-based, optimal control algorithms introduced by later work [@bolus21] (see @sec-prev-work) for unidirectional actuation.
This adaptive linear-quadratic regulator (LQR) approach is more robust to disturbances and can scale to multi-input multi-output (MIMO) systems.
Moreover, its behavior can be easily configured by setting penalties on state error, the control signal, and even the derivative of the control signal to encourage smooth actuation.

### Challenges of combining
Thus, a natural goal for furthering CLOC is to combine the advantages of bidirectional actuation and model-based optimal control---however, this poses additional challenges and opportunities.
Unfortunately, the adaptive LQR method previously developed is unsuitable for bidirectional actuation because it does not model the constraint that the input (light intensity) must be nonnegative. 
While violations of this constraint are relatively infrequent and of little consequence when using an excitatory opsin to reach elevated, slowly varying trajectories, a bidirectional input scenario would be different.
For instance, the controller might call for negative inhibitory input rather than positive excitatory input---a problem that might be solvable with heuristics for the simplest cases but which would pose serious limitations with increasing actuator count.

:::{.callout-caution}
## Questions
How do I know I want to continue using an LDS? At what point would I want to go for something like a Hammerstein-Wiener models for input/output nonlinearities? Or an ANN dynamics model
:::

### Innovation
I propose addressing this problem using model predictive control (MPC), which is widely used for its flexibility in implementing optimal control with constraints.
Rather than computing the control signal from the current error signal at each step, MPC looks ahead, optimizing over the predicted trajectory some finite number of steps into the future, in what is known as "receding horizon control."
I hypothesize that a model predictive strategy will be able to optimize bidirectional optogenetic actuation while accommodating experimental constraints and considerations and maintaining low error levels during fast, real-time control.
I plan to achieve this aim by adapting previously demonstrated linear models, adding constraints and costs, and accelerating as needed.
Using the simulation framework from @sec-aim1, I will evaluate controller performance and prolonged stimulation avoidance compared to previous approaches.

## Model formulation
### Approach
#### Linear-quadratic-Gaussian problem

### Preliminary results

### Expected results

### Potential pitfalls, alternative strategies


## Abstract proof of concept

### Approach

### Preliminary results

### Expected results

### Potential pitfalls, alternative strategies


## Demonstration in spiking neural network simulation

### Approach

### Preliminary results

### Expected results

### Potential pitfalls, alternative strategies


## Acceleration for real-time use

### Approach

### Preliminary results

### Expected results

### Potential pitfalls, alternative strategies
