# Background

## Closed-loop control in neuroscience {#sec-cl-neuro}

Mesoscale neuroscience is currently undergoing a revolution fueled by advances in neural manipulation [@fenno11; @wiegert17; @sridharan22; @vierock21; @adesnik21; @faini21; @roth16; @eriksson22] and measurement [@steinmetz21; @siegle17; @gutruf18; @gobel07; @knopfel19; @svoboda06; @kazemipour19; @wu20a] technologies as well as data analysis methods [@maaten08; @berman14; @mathis18; @sani21a; @sporns18; @schneider22]. 
These have yielded unprecedented datasets [@scheffer20; @juavinett19] and insights into network activity and plasticity [@oby19; @yang21; @cowley20; @avitan22; @jazayeri21], as well as novel experimental paradigms such as direct closed-loop control of neural activity [@grosenick15; @kumar13; @potter14; @newman15; @bolus18; @bolus21; @emiliani15; @zhang18; @krook-magnuson13; @witt13; @dutta19]. 

An exciting emerging possibility is closed-loop control of neural activity [@grosenick15; @other-reviews], enabling intervention in processes that are too fast or unpredictable to control manually or with pre-defined stimulation, such as sensory information processing, motor planning, and oscillatory activity. Unlike other forms of closed-loop control altering the environment [cite examples, mouse knee rotation, visual stimuli to achieve target response,] or using neurofeedback training [cite Diester] to achieve a neural or behavioral target, the direct control of neural activity itself can unambiguously reveal the downstream effects of that activity.

Closed-loop control of neural activity can be implemented in an event-triggered sense [cite a bunch of examples, inhibiting seizures, altering power, SWR disruption, ]---enabling the experimenter to respond to discrete events of interest, such as the arrival of a traveling wave [cite Reynolds] or sharp wave ripple [cite some review paper]---or in a feedback sense [cite 2 Bolus papers, all-optical, any others], driving the system towards a target or along a trajectory. The latter has multiple advantages over open-loop control (delivery of a pre-defined stimulus): by rejecting exogenous inputs, noise, and disturbances, it reduces variability across time and across trials, allowing for finer-scale inference. Additionally, it can compensate for model mismatch, allowing it to succeed where open-loop control based on imperfect models is bound to miss the mark.

## Various scales and tools for closed-loop control

Closed-loop control of neural activity can be performed at multiple scales and with different sets of tools.
At the smallest, sub-neuron scale, dynamic clamping has yielded decades of fruitful research [@hodgkin53; @cite some-review-paper] in the forms of tools such as the dynamic clamp and voltage clamp, controlling electrical properties of small patches of membrane. 
The frontiers of this small-scale neuroscience often involve scaling up to multiple neurons and scaling down to subcellular structures such as dendrites [@cite], but multi-electrode intracellular recording face limitations [@davie06; @wang15; @engel16; @cite more, not just patch clamping].
Optical tools---e.g., optogenetics and fluorescence microscopy---can circumvent the difficulties of working with electrodes at such small scales, but an optical approach is not yet feasible for this purpose.
The obstacles lie mainly in recording technology: the kinetics of both voltage indicators [@wu20a] and intracellular calcium [@cite] are too slow to capture phenomena faster than a typical action potential. 

By contrast, the current state of technology is ripe for innovating closed-loop control methods at larger scales of neural activity, from single neurons to populations and circuits.
Several promising combinations of recording and stimulation modalities are possible and still relatively novel: electrode recording with optogenetic stimulation [@cardin10, our papers], fluorescence microscopy with electrical stimulation [@cite], fluorescence microscopy with photostimulation (all-optical control) [@hochbaum14; @emiliani15; @zhang18; @kishi22], and fMRI with optionally transcranial [@lin13; @chen18a] photostimulation.
Each of these tool combinations has pros and cons in terms of spatial and temporal resolution, crosstalk [@packer13], and degrees of freedom.

A natural starting point for many neuroscientists is the first of these tool sets—electrode recording combined with optogenetics—since the two methods are so widely used, interfere little with each other (as long as metal electrodes are not directly illuminated [@cardin10; @packer13]), and allow for genetically targeted stimulation.
I will henceforth refer to this combination as CLOC, following the convention established by previous works [@bolus18; @bolus21].

## Previous CLOC work
:::{.callout-caution}
TODO
:::

## Potential applications in mesoscale neuroscience
Seeing that a suitable technological foundation for feedback control of neural activity has already been laid with CLOC, I turn now to a discussion of several exciting areas where CLOC could further causal hypothesis testing.
These deal with concrete questions of scientific interest, as opposed to the conceptual/technical advantages previously explained (@sec-cl-neuro).
Neuroscientists often identify specific variables or phenomena to assess their role in a larger neural system, in search of interpretable components of brain activity.
A natural application of CLOC is to control these variables and phenomena of interest directly to enable stronger inference of their relationship to downstream variables.
Examples of these potential targets for control include the activity of different cell types [@martinez-garcia20; @more]; the type [@cole17; @cole19; @fabus21], frequency [@saleem17], amplitude [@saleem17], spike coherence [@buschman12; @buffalo11] and relationship [@aru15; @zhang19] of different oscillatory patterns [@buzsaki04]; discrete phenomena such as bursts [@cite], sharp wave ripples [@buzsaki15], oscillatory bursts [@lundqvist16; @lundqvist22; @eriksson22], traveling waves [@muller18; @davis20], or sleep spindles [@cite]; and latent states describing neural dynamics [@vyas20; @cite 2021 review, Shenoy lab causal test, Hantman], including those most relevant to behavior [@sani21a; @sani21; @hurwitz21].

While some of these targets lend themselves easily to CLOC, others require continued innovation in interfacing technology.
While recent advances in recording technology allow us to infer neural state with unprecedented precision [@steinmetz21; @siegle17; @calcium-imaging; @kazemipour19; @wu20a; @GEVI], available actuation technologies are much more limited in their degrees of freedom and thus unlikely to sufficiently control what is observed.
For this reason, the development of micro-LED arrays [@cite], multi-channel optrodes [@eriksson22], and holographic optogenetic stimulation [@zhang18; @cite] are of particular interest.
Moreover, rigorous investigation of the importance of recording and stimulation capabilities relative to each other would be helpful in guiding technological development and experimental design.

In addition to controlling variables of interest, CLOC can serve a paradigm of decoupling variables.
This could be in the context of a circuit, where clamping the activity of a given node decouples its activity from all inputs except for the controller.
This functionally severs links in the circuit, aiding in circuit identification and in testing the function of different nodes and connections [@willats-clinc].
Moreover, CLOC could be used in the more general sense of controlling for confounding variables.
For example, one might want to manipulate the synchrony of a population without changing the mean firing rate, or vice-versa.
Whereas the conventional open-loop stimulation approach might accomplish this through tedious titration of stimulation parameters [@nandy19], the feedback control approach could simultaneously manipulate both variables as desired, requiring only a passable model of the system.

## Innovation
:::{.callout-caution}
TODO
:::

Despite CLOC's great promise to be applied in these areas, it has not yet been widely applied in mesoscale neuroscience. 
As previously explained (@sec-aims), I identify three main reasons