---
format:
  html:
    toc: false
tbl-colwidths: [38, 62]
---
# Abstract
As the importance of causal inference becomes increasingly recognized in neuroscience, the need for technology enabling precise manipulation of neural variables becomes apparent.
Feedback control is an important class of such manipulations for its ability to increase inference power by reducing response variability.
Widely used throughout the engineering disciplines, it has had a significant impact through a variety of techniques (e.g., voltage clamp, dynamic clamp) on cellular neuroscience.
However, feedback control has yet to be widely applied at the mesoscale/circuit level despite recent improvements in interfacing technology, such as optogenetics.
Challenges to adoption include the complexity of implementing fast closed-loop experiments, the need to adapt the mature methods of control theory to the idiosyncratic constraints of systems neuroscience experiments, and the lack of established technical guidelines for applying feedback control to address complex scientific questions.

In this work I propose to begin to address these challenges in three aims.
In Aim 1, I develop a simulation framework for easily prototyping closed-loop optogenetic control (CLOC) experiments *in silico*, thus allowing neuroscientists to test and iterate on experimental designs without the costs of in-vivo experiments or up-front investments in compatible hardware-software systems.
In Aim 2, I will translate sophisticated model-based feedback control algorithms to the realistic experimental setting of multi-input CLOC---the simultaneous use of multiple light sources, which includes the bidirectional case of both excitatory and inhibitory opsins.
I will demonstrate some advantages of multi-input CLOC and test the virtues of more powerful and complex algorithms compared to the limited, simpler ones previously used.
Finally, in Aim 3, I will explore how control quality varies with experimental parameters in a promising future application of CLOC---controlling the latent dynamics of simulated neural population activity---and test the hypothesis that per-neuron actuation will not be needed.
I will model this population activity with recurrent spiking neural networks trained using state-of-the-art, biologically plausible methods, with differing degrees of brain-like architecture and task complexity.
This work will thus provide the systems neuroscience community with a more accessible entry point for CLOC, more powerful algorithms for leveraging multi-input control, and a point of reference for designing CLOC experiments capable of answering complex scientific questions.

<!-- ::: {.hidden}
# Front Matter {.unnumbered}
::: -->

:::{.content-hidden when-format="pdf"}

## Thesis committee {.unnumbered}

+------------------------:+:-----------------------------------------------------+
|    Nabil Imam           | Georgia Institute of Technology \                    |
|                         | Computational Science and Engineering                |
+-------------------------+------------------------------------------------------+
|    Chethan Pandarinath  | Emory University & Georgia Institute of Technology \ |
|                         | Biomedical Engineering                               |
+-------------------------+------------------------------------------------------+
|  **Christopher Rozell** | Georgia Institute of Technology \                    |
|     **(advisor)**       | Electrical and Computer Engineering                  |
+-------------------------+------------------------------------------------------+
|   Garrett Stanley       | Georgia Institute of Technology & Emory University \ |
|                         | Biomedical Engineering                               |
+-------------------------+------------------------------------------------------+
|   Patricio Vela         | Georgia Institute of Technology \                    |
|                         | Electrical and Computer Engineering                  |
+-------------------------+------------------------------------------------------+

:::