# Summary {.unnumbered}

Mesoscale neuroscience is currently undergoing a revolution fueled by advances in neural manipulation [@fenno2011; @wiegert2017; @sridharan2022; @vierock2021; @adesnik2021; @faini2021; @roth2016; @eriksson2022] and measurement [@steinmetz2021; @siegle2017; @gutruf2018; @gobel2007; @knopfel2019; @svoboda2006; @kazemipour2019; @wu2020] technologies as well as data analysis methods [@maaten2008; @berman2014; @mathis2018; @Sani2021a, sth with graph theory]. These have yielded unprecedented datasets [cite mouse atlas, worm connectome, Neuropixels dataset, …] and insights into network activity and plasticity [cite Byron Yu BCI learning, Shanechi multi-region sim, Stringer V1, Cowley slow drift, Jazayeri & Ostojic], as well as novel experimental paradigms such as direct closed-loop control of neural activity [cite Grosenick, other reviews, feedback: our papers, all-optical; event-triggered: inhibiting seizures, altering power, SWR disruption]. 


An exciting emerging possibility is closed-loop control of neural activity [cite Grosenick, a bunch of other reviews], enabling intervention in processes that are too fast or unpredictable to control manually or with pre-defined stimulation, such as sensory information processing, motor planning, and oscillatory activity. Unlike other forms of closed-loop control altering the environment [cite examples, mouse knee rotation, visual stimuli to achieve target response,] or using neurofeedback training [cite Diester] to achieve a neural or behavioral target, the direct control of neural activity itself can unambiguously reveal the direct downstream effects of that activity.

Closed-loop control of neural activity can be implemented in an event-triggered sense [cite a bunch of examples, inhibiting seizures, altering power, SWR disruption, ]—enabling the experimenter to respond to discrete events of interest, such as the arrival of a traveling wave [cite Reynolds] or sharp wave ripple [cite some review paper]—or in a feedback sense [cite 2 Bolus papers, all-optical, any others], driving the system towards a target or along a trajectory. The latter has multiple advantages over open-loop control (delivery of a pre-defined stimulus): by rejecting exogenous inputs, noise, and disturbances, it reduces variability across time and across trials, allowing for finer-scale inference. Additionally, it can compensate for model mismatch, allowing it to succeed where open-loop control based on imperfect models is bound to miss the mark.
