# Specific Aims {#sec-aims}
<!-- think of this as an extended abstract -->

## Rationale {#sec-aims-rationale}
As the importance of causal inference becomes increasingly recognized in neuroscience, the need for technology enabling precise manipulation of neural variables becomes apparent.
Feedback control is an important class of such manipulations for its ability to increase inference power by reducing response variability.
Widely used throughout the engineering disciplines, it has had a significant impact through a variety of techniques (e.g., voltage clamp, dynamic clamp) on cellular neuroscience.
However, feedback control also has great potential at the mesoscale/systems level, potentially enabling researchers to *unambiguously infer the downstream effects of circuit/population-level neural activity*.

For a number of reasons, though, *this potential has not been widely realized*.
<!-- The main challenges to wider adoption do not appear to lie with available technology, as the requirements of feedback control are beginning to be met by the ever-improving computational power and stimulation/recording tools (such as optogenetics and large-scale neural recording) already available to neuroscientists. -->
I posit that the main challenges to adoption rather include the **complexity of implementing** fast closed-loop experiments, the need to **adapt the mature methods of control theory** to the idiosyncratic constraints of systems neuroscience experiments, and the **lack of established technical guidelines** for applying feedback control to address complex scientific questions.
**The proposed work aims to begin to address these challenges, and thus strengthen the set of causal tools available to probe neural systems.**

## Aim 1: A CLOC experiment simulation testbed
One significant obstacle to closed-loop optogenetic control (CLOC) experiments is the cost of acquiring and configuring compatible hardware-software systems. 
Moreover, the maintenance of animals or cell cultures inherent in lab experiments can slow the pace of developing novel techniques.
In Aim 1, I attempt to address these obstacles by developing a simulation framework for easily prototyping CLOC experiments _in silico_, thus enabling faster, cheaper CLOC experiment design and method development.
We demonstrate the software's utility in different virtual experiments and provide it to the public as open-source software with thorough documentation.

## Aim 2: Multi-input CLOC
Multi-input CLOC---the simultaneous use of multiple light sources and/or opsins---is necessary for precise manipulation of neural systems.
However, the basic control theory methods previously used for CLOC, while fast, do not take actuator constraints into account and are thus likely to be inadequate for multi-actuator problems.
The field of control theory provides elegant, powerful---if slower---solutions to this class of problems, but applying them requires interdisciplinary expertise.
In this aim I will translate more sophisticated model-based feedback control algorithms to the multi-input CLOC setting and assess their merits compared to limited, simpler methods *in silico* for real-time control of brain networks.

## Aim 3: Using CLOC to manipulate latent neural dynamics
To our knowledge, CLOC has yet to be applied in answering complex systems neuroscience questions.
In this aim, to pave the way for future *in-vivo* experiments that accomplish this, I propose to develop technical and conceptual guidelines as I control the latent dynamics of simulated neural populations.
First, I will produce these virtual models by training recurrent spiking neural networks with state-of-the-art, biologically plausible methods---each differing in their degrees of brain-like architecture and training procedure complexity.
I will then use the simulation testbed of Aim 1 to explore how control quality varies with recording, stimulation, and control parameters and the complexity and size of the system---thus giving researchers a tentative idea of the relative importance of each factor of CLOC.
I will test the hypothesis that low-dimensional dynamics can be manipulated with similarly low-dimensional, rather than per-neuron, actuation.